### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by hjanuschka**
fix for symfony3

### CODE REVIEW

**Comment by hpatoio** [comment]
Hello @hjanuschka shouldn't be better to have 

`"symfony/framework-bundle": "~2.0|~3.0",` ? So it can works with both symfony2 and 3. What do you think ?

**Comment by hjanuschka** [comment]
absolutly true, changed it with another commit ;)

**Comment by hpatoio** [comment]
Great but please squash your commits.

**Comment by hjanuschka** [comment]
done!

**Comment by hpatoio** [comment]
Great. Merged. Gonna tag a minor release ASAP

**Pull request merged**
